python/psf-salt

salt/consul/etc/consul-template/template.json.jinja

Simple formatting change which keeps 'command =..' in a new line (instead of joining it with 'destination = ..' line)

better formatting for consul-template/template.json.jinja

---

salt/pydotorg/init.sls

I've been moving Python.org to Django 1.7, this changes how migrations are done.  Moving from pre-1.7 syncdb to post-1.7 migrate.

Move to Django 1.7 migrate changes

---

salt/pydotorg/config/pydotorg.nginx.jinja

The jobs app will go live this week and it will be hosted at
/jobs/.
Update the old Jobs.html redirect to the new location.

Remove the /jobs/ redirect

---

salt/pydotorg/config/pydotorg.nginx.jinja

We used to run the jobs app under /newjobs during development
and had the RSS feed URL public for a short while. The redirect
should enable us to remove the second location of the jobs app,
avoiding duplicate URLs for every single job posting.

Redirect /newjobs URLs to /jobs

---

salt/pydotorg/init.sls

Creates directory inside media and sets up nightly 1am cron job to generate development fixtures.

Generate pydotorg dev fixtures

---

salt/pycon/config/htpasswd
salt/pycon/config/pycon.nginx.jinja
salt/pycon/init.sls

Until we're ready, require a userid and password to
access the /2016/ part of the Pycon site.

Add basic auth to /2016 part of Pycon site

---

pillar/prod/backup/server.sls

Increase from 14 days to 90
Fixes #53

Keep PyCon prod DB backups longer

---

salt/pycon/config/pycon.nginx.jinja
salt/pycon/init.sls

Looks like @brandon-rhodes has been notified that staging sites are being indexed by Google and confusing users searching for PyCon 2016 RFP.
This should stop the indexing and we can request the existing results are removed.

add X-Robots-Tag to staging responses

---

salt/pycon/init.sls

It didn't occur to me that the servers might not have it already.
Note: I don't think the servers will be restarted by deploying this, since that only happens when source changes, so we might need to do that manually.

Make sure Pycon servers have en_US.UTF-8 locale

---

pillar/base/firewall/postgresql.sls
pillar/base/tls.sls
salt/firewall/config/iptables.jinja
salt/postgresql/server/configs/pg_hba.conf.jinja
salt/postgresql/server/configs/postgresql.conf.jinja
salt/postgresql/server/configs/stunnel.conf.jinja
salt/postgresql/server/if-up.sh
salt/postgresql/server/init.sls
salt/stunnel/configs/default.sh
salt/stunnel/init.sls

PostgreSQL doesn't offer the ability to gracefully reload the TLS certificate, which requires a hard restart whenever the certificate is close to expiring. This generates errors because it interrupts current connections. Instead, we'll utilize stunnel to terminate TLS which does support a graceful reload.
We'll also rely on iptables able to mangle packets to spoof the source address on the packets sent from stunnel to PostgreSQL so that PostgreSQL still sees the correct IP address. However, PostgreSQL does not understand that the connections are happening via TLS so things like ``hostssl`` doesn't work. Stunnel will not allow a connection that does not use TLS though, so the rule is still effectively there.
This also relaxes the firewall and what IP addresses we bind the PostgreSQL server …

Revamp postgres tls

---

Vagrantfile

This ensures that salt-master is actually running before attempting to
do `salt-call state.highstate`.
Without this, `vagrant reload salt-master` fails every time for me.

Always restart salt-master service at provision tme

---

salt/docs/config/nginx.docs-backend.conf

Apparently, the old URL scheme still in use in the internet. See
https://github.com/python/pythondotorg/issues/884 for example.
I might better to redirect http://docs.python.org/tut/ to the Python 3
tutorial at this point.

Redirect docs.p.o/tut/ to the Python 3 tutorial

---

salt/docs/config/nginx.docs-backend.conf

I saw complaints about this on Reddit and Hacker News before.
Here is the latest one: https://asmeurer.github.io/blog/posts/moving-away-from-python-2/#fn:core

Redirect toplevel URIs to Python 3 docs

---

salt/pydotorg/init.sls

Please do not accept this PR until the peps repository has been migrated to GitHub. Creating this PR now to get a code review that it's accurate for when it's time to do the actual migration.

clone peps from GitHub

---

salt/docs/init.sls

Build the docs using git instead of hg.
Do not merge this until CPython development has migrated to GitHub!

build docs using git

---

pillar/base/firewall/ftp.sls
pillar/prod/top.sls
salt/pythontest/config/vsftpd.conf
salt/pythontest/init.sls

This is my first time using salt, though not my first time using an orchestration tool. I tested locally on an ubuntu-14.04 server VM. I'd appreciate any feedback if I made any glaring mistakes.
This installs and configures the vsftpd package. The running server is configured to only allow anonymous logins, all write commands are disabled at the ftp dameon level. See the `write_enable=False` option, in addition to setting the ftp folder to be `-w` by all. This makes it so that the entire ftp server is read-only. 
In order to allow ftp through the firewall I've used ports 10090 to 10100, ftp needs to have open incoming ports to allow for data transfers. The alternative to using these fixed ports is to use a kernel module that hooks into iptables and snoops on ftp connections to dynamically …

Enable a simple read-only FTP server on pythontest

---

salt/docs/config/nginx.docs-backend.conf

Currently https://docs.python.org/fr/ gives a directory listing. As / is redirecting to /3/, I'm also redirecting /fr/ to /fr/3/.

Redirect root of translations (like /fr/) to their 3 version

---

salt/docs/init.sls

we can migrate scripts over by changing their path, then remove the old virtualenv later.
addresses #109

docs: create a new virtualenv with python3

---

salt/docs/config/nginx.docs-backend.conf

https://docs.python.org/ja/3.6/ is successfully build, now needs the redirection to avoid directory listing on https://docs.python.org/ja/.

docs.python.org: Add Japanese in nginx redirections.

---

salt/docs/init.sls

Since https://github.com/python/docsbuild-scripts/commit/c7181345d6735f6315f522a97ccb3031d320f08c which is already deployed, the --git flag is the default.

docsbuild-scripts: Dropping now default --git flag

---

salt/pydotorg/config/pydotorg.nginx.jinja

I don't know whether https://github.com/python/psf-salt/blob/master/salt/haproxy/config/haproxy.cfg.jinja is a better place to put this so I went with `salt/pydotorg/config/pydotorg.nginx.jinja`.

Set x-xss-protection header on pydotorg

---

salt/pydotorg/config/django-settings.py.jinja

We need to set this on staging.p.o because the is_same_domain() function
returns true only when the hostname of the referer is an exact match of
CSRF_COOKIE_DOMAIN.
In our case it returns false because "staging.python.org" is not an
equivalent of "staging.python.org:9000" and as a result we get a 403 error.
See https://github.com/django/django/blob/e7adad27f30396823f3609fcb8699cefb25278bb/django/middleware/csrf.py#L273
for details.

Set CSRF_TRUSTED_ORIGINS for staging.p.o

---

salt/docs/init.sls

If this venv was only used by docsbuild-scripts, it's no longer used since https://github.com/python/docsbuild-scripts/commit/90ed1d08bbba10c972cfd4d1526f4776c295a13a.
This will not remove the no longer used files on the server (`/srv/docsbuild/environment/`), is there a policy to do it via salt, or manually?

docs: This venv is no longer used.

---

salt/docs/init.sls

xelatex has better Unicode support than pdflatex, sufficient to build
french, but not to build japanese. But we already have platex, capable
to build japanese, installed from texlive-lang-japanese pulled as a
dependency of texlive-lang-all.
See:
- https://github.com/sphinx-doc/sphinx/issues/4136
- https://github.com/python/cpython/pull/3940

Add xelatex to help building french PDFs.

---

salt/docs/config/nginx.docs-backend.conf

The old configuration was redirecting only for:
curl -I 'https://docs.python.org/devguide/(*)'
See https://bugs.python.org/issue30737

FIX 301 to the new devguide.

---

salt/docs/config/nginx.docs-backend.conf

This was reported at https://twitter.com/zzzeek/status/963804209618571264

Redirect /searchindex.js and /objects.inv to /3/

---

salt/pydotorg/init.sls

We've upgraded Pillow version to 5.1.0 in
https://github.com/python/pythondotorg/commit/21ecdc2289e4f4b64b936394bd3f1c5171f6bd73
Pillow requires JPEG support since 3.x so we need to
install libjpeg-dev.

Install libjpeg-dev for Pillow

---

salt/postgresql/server/configs/wal-e.conf.jinja
salt/postgresql/server/wal-e.sls

updates wal-e to latest, sets cleanup job to run weekly retaining 6 weeks of backups

wal-e cleanup/updates

---

salt/docs/config/nginx.docs-backend.conf

docs.python.org/zh-{cn,tw} are available now.

Adding configuration for zh-{cn,tw} translation of the documentation

---

salt/docs/init.sls

By just using the global Python we're not having sentry installed.
But using the venv directly is fine: we'll get sentry, and it would simplify passing the venv to subprocesses. Which is supported down to the Makefile since https://github.com/python/cpython/commit/590665c399fc4aa3c4a9f8e7104d43a02e9f3a0c#diff-c8dee9c3c068ad3447bbf459950a35b5 which is nice.

Docs: Directly jump in venv to get sentry.

---

salt/docs/config/nginx.docs-backend.conf

We're having like 100 hits per day on this one according to ```zcat /var/log/nginx/docs-backend.access.log.{2..7}.gz | awk '{if ($9 == 301) {print $7}}' | grep -P '^/((2|3)(\.[0-8])?|dev)/\w+/[\d\w\.]+(?!\.html)$' | wc -l```
Some are bots, some are humans using it as a feature (maybe like 1 of 2).

Docs: Will probably never remove this one.

---

salt/docs/config/nginx.docs-backend.conf

On the backend we're having ~100 hits per day on */library/sets.html. This is (behind some "/apple-touch-icon.png" and co.) the most frequent 404 on the docs.
Those are people searching "sets" on search engines, landing on https://docs.python.org/2/library/sets.html, changing the version on the version switcher. At this moment the switcher script tries to hit the URL and get a 404 (this page no longer exist on new versions), so the script redirects the user on /, which is ... as not as helpfull as it can be.

Smooth the switch between sets.html and stdtypes.html

---

salt/docs/init.sls

rebase of #160 on the 18.04 universe branch.

Doc: Missing latexmk dependency

---

salt/docs/init.sls

Looks like we're missing this dependency, from the logs I see:
```
Can't exec "xindy": No such file or directory at (eval 10) line 14.
```

Doc: Missing xindy dependency.

---

pillar/base/users.sls

Used to have shell access to old bugs.python.org, we recently had a spam event where I wrote a spam removal script, in this case John Rouillard already removed the spam but there will be others.

Allow schlatterbeck access to roundup tracker

---

salt/docs/init.sls

see https://github.com/python/docsbuild-scripts/issues/68
Also I don't think it's usefull to have docs updated every 3 hours, apart from /dev/, they change very slowly.
Also now that we have translations, it's not 6 versions that we're building but 6 versions × 6 languages, it starts to be CPU heavy.
I'm sure we can do better, but in the meantime it should fix 404s that we're getting on every releases.

Docs: Remove quick cron: on version bumps they cause 404s.

---

salt/hg/files/hg/src/hglookup.py

Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.

Use print() function in both Python 2 and Python 3

---

salt/docs/init.sls

This is in case I finish a current implementation where docsbuild-scripts manage its venv itself.
It could be a good thing: allowing to have multiple venvs, with multiple versions of sphinx, thus allowing to still buid old versions of Python which do no longer build with current sphinx.
Eventually, I hope to reach a cleaner state where:
- docsbuild-script's requirements are only its own requirements (mostly sentry)
- it handles build requirements itself (`jeiba`, `sphinx`, `blurb`, `python-docs-theme` ...)
Currently both are mixed in the requirements.txt file.

docsbuild-scripts: Make python3 -m venv work.

---

salt/docs/config/nginx.docs-backend.conf

Related to https://bugs.python.org/issue42869
This should make `https://docs.python.org/3.9/library/functions` redirect like `https://docs.python.org/3.8/library/functions` does.
Currently:
```
$ curl -i https://docs.python.org/3.8/library/functions | head -n 1
HTTP/2 301 
$ curl -i https://docs.python.org/3.9/library/functions | head -n 1
HTTP/2 404 
```
Beware, I did *not* tested it locally.

Doc: Hello Python 3.9 and 3.10.

---

salt/pypa/bootstrap/init.sls

see: https://github.com/pypa/get-pip/issues/61

expose get-pip's "public" folder at bootstrap.pypa.io/pip

---

salt/docs/config/nginx.docs-backend.conf

See https://github.com/python/cpython/pull/24195 and https://github.com/python/pythondotorg/issues/1719
Also see https://github.com/verhovsky/py3redirect/blob/master/special-cases.js for a list of anchors that have been moved.
Generated using the following code:
```py
moved_files = {
"library/fpformat": None,
"library/mutex": None,
"library/new": None,
"library/statvfs": None,
"library/dircache": None,
"library/macpath": None,
"library/dbhash": None,
"library/bsddb": None,
"library/someos": None,
"library/popen2": None,
"library/mhlib": None,
"library/mimetools": None,
"library/mimewriter": None,
"library/mimify": None,
"library/multifile": None,
"library/sgmllib": None,
"library/imageop": None,
"library/hotshot": None,
"library/future_builtins": None,
"library/user": None, …
```

Redirect all 2.7 files removed in Python 3

---

salt/pypy-web/init.sls

Please check carefully, this is my first PR here.
The rendered website for https://pypy.org is now created on the gh-branch of https://github.com/pypy/pypy.org. This is to enable blogs via nikola and the commenting system via the [utterances](https://utteranc.es/) javascript plugin, which interfaces with github.

move pypy.org base repo to github

---

salt/pypy-web/init.sls

In order to reduce git churn, we force push the gh-pages branch. So the local checkout must use `force_checkout` and `force_fetch`.

force checkout the gh-pages branch, which is force-pushed

---

pillar/base/bugs.sls

Move the IRC bot irker from Freenode #python-dev to Frenode

Closes #208: Move irker to #python-dev-notifs

---

salt/bugs/config/nginx.conf.jinja

Data returned from the roundup servers is not compressed. Set up nginx to compress the data on the fly.
I overrode the default compression level from 1 to 6 as that seems to provide the best compression ratio/cpu time
on the roundup assets on my system. But lowering that is the system is too stressed works too.
I am not sure if there is an additional proxy upstream, so I enabled gzip_vary. It may not be needed.
Made sure to include xml as a compressed type as the RSS feed uses it.

Setup nginx to compress responses from roundup trackers.

---

salt/docs/config/nginx.docs-backend.conf

https://docs.python.org/3.7/library/macpath.html redirects, but the file exists:
```
mdk@docs:~$ file /srv/docs.python.org/3.7/library/macpath.html 
/srv/docs.python.org/3.7/library/macpath.html: HTML document, UTF-8 Unicode text, with very long lines
```

d.p.o/3.7/library/macpath.html does in fact exists.

---

salt/docs/init.sls

@JulienPalard I assume we also need to update some of the other references in this file?

add deadsnakes and install python3.10 for docs.nyc1.psf.io

---

pillar/base/bugs.sls
salt/bugs/init.sls
salt/hg/init.sls

This PR removes all mentions of irker that I found.
AFAIK it was only used by bpo, so removing it should be safe.
This should be merged after the migration is completed.

Remove irker.

---

salt/docs/config/nginx.docs-backend.conf

I'm working on https://github.com/python/docsbuild-scripts/issues/127
The idea is to avoid mails to docs@ telling the PDFs are 404ing.
We had "a lot" of them back then when we were building the PDF daily and the docs hourly. We have less now than we build the PDF at the same rate as the HTML (the html not pointing to an existing PDF lives for less time, but HTML is still build before PDF so users can still hit the 404).
It would allow to get back at the previous state where we were buildling the PDF less often, which would allow for faster HTML builds, for the joy of HTML readers (and the pain of PDF readers maybe).

docs: Display a nice 404 when archives are not built yet.

---

salt/docs/init.sls

- stopped installing pythons from the distro, relying on deadsnakes ppa
- bootstrap pip via venv module instead of get-pip

Update the state file for docs to accomodate ubuntu 20.04

---

salt/consul/etc/_address_list.jinja
salt/consul/etc/join.json.jinja
salt/consul/etc/server.json.jinja

we need to handle the join list _and_ bootstrap_expect for dev, but it is helpful in bootstrapping clusters in deployments.

correctly handle the number of consul hosts available

---

salt/bugs/cpython.sls
salt/bugs/init.sls
salt/bugs/postgresql.sls
salt/bugs/roundup.sls

- Update state so locally it works with the local lets encrypt service from #258
- Install/configure Python2.7 explicitly, as that is what roundup supports
- Resolve various dependency/requirement issues that stop this state from working from scratch.

Upgrade bugs state for Ubuntu 20.04

---

salt/downloads/init.sls

invocation: `tox -e lint $(find salt/downloads -type f -name '*.sls'| xargs)`

salt-lint salt/downloads directory

---

salt/docs/init.sls

invocation: `tox -e lint $(find salt/docs -type f -name '*.sls'| xargs)`

salt-lint salt/docs directory

---

pillar/base/haproxy.sls
pillar/prod/roles.sls

Configures role for new hostname and adds a health check to ensure the new moin server doesn't get traffic until we are ready.

Prepare for moin migration to 20.04

---

pillar/base/haproxy.sls
pillar/prod/roles.sls

Configure health check and modify pillar/prod/roles.sls compatibility for migration of docs to ubuntu 20.0.4

Get docs ready 2 migrate 

---

pillar/prod/backup/bugs.sls
pillar/prod/backup/buildbot.sls
pillar/prod/backup/docs.sls
pillar/prod/backup/downloads.sls
pillar/prod/backup/hg.sls
pillar/prod/backup/mail.sls
pillar/prod/backup/moin.sls
pillar/prod/backup/server.sls
pillar/prod/top.sls
salt/backup/client/init.sls

this ensures that backup config is viewable by all users, and can be updated by anyone.

backups: move all but private-key to public pillar data

---

pillar/prod/roles.sls
salt/downloads/init.sls

1) update pattern for downloads role
2) don't create _check file for HTTP health check, so that new host will not join loadbalancer

prepare downloads role for migration

---

salt/tls/pebble.sls

When bringing up the salt-master locally, the pebble-source state `git.latest` function fails with this comment: `Repository would be updated from 087582e to d5fa738, but there are uncommitted changes. Set 'force_reset' to True (or 'remote-changes') to force this update and discard these changes.`
By defualt, `git.lastest` `force_reset` is set to false. By changing our configuration to use `force_reset: remote-changes`, we can instruct[ salt](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.git.html#:~:text=in%20version%202015.8.0.-,force_resetFalse,-If%20the%20update) not to discard local changes if the repo is up-to-date with the remote repository.

pebble-source state failing

---

salt/base/repo.sls
salt/bugs/postgresql.sls
salt/datadog/init.sls
salt/nginx/init.sls
salt/postgresql/base/init.sls

Removing trailing slash on `pkgrepo.managed` URLs to prevent states from always reporting changed. This addresses issue #299 with reference to https://github.com/saltstack/salt/issues/58781

Removing trailing slash on `pkgrepo.managed` URLs 

---

pillar/base/users.sls
salt/users/init.sls

Adding a default option to prevent returning an empty string to `match.compound` removing error addressed in #297
Note: this locks up `devnull.psf.io` from being used in the future.

Add a default option 

---

pillar/base/haproxy.sls
salt/base/config/publish-files-nginx.conf
salt/base/salt.sls

Configure salt to manage psf_known_hosts and salt-server-list.rst and serve them via HTTP

Configure salt to manage psf_known_hosts and salt-server-list.rst

---

salt/docs/init.sls

see: https://github.com/python/python-docs-ja/issues/31#issuecomment-1465791751
I'm trying it manually before, to ensure that's why we need, nothing more is needed, and it actually fix the proble, so please don't merge now.

Adding needed font for ja PDF builds.

---

salt/docs/config/nginx.docs-backend.conf

The `^~` modifier makes this rule take priority priority over regex
(specifically the `pdf|zip|epub|bz2` regex above), see
https://nginx.org/en/docs/http/ngx_http_core_module.html#location
See: https://github.com/python/cpython/issues/95290

Fix /ftp redirect on docs.python.org for archives

---

salt/docs/init.sls

The script will just die soon if another insance already runs (it uses a file lock), so there's no fear at starting it too often.
Also the script does no longer build documentation that has not changed (by checking the cpython and translation shas), so runnig the script more often will not introduce more load, just faster builds.
closes #320.

docs: Build more often.

---

pillar/base/haproxy.sls
salt/hg/init.sls

These changes prepare hg for future X-Forwarded-For, and rate-limiting configurations. 
To test that this is working locally: 
1. bring up the salt-master, `laptop:psf-salt user$ vagrant up salt-master`
2. bring up the loadbalancer, `laptop:psf-salt user$ vagrant up loadbalancer`
3. bring up hg, `laptop:psf-salt user$ vagrant up hg`
4. in another window, ssh into the vagrant hg box, `vagrant shh hg`
5. install curl `sudo apt install curl`
6. to test localhost, `for i in {1..20}; do curl -o /dev/null -s -w "%{http_code}\n" -k -H "Host: hg.python.org" https://127.0.0.1:9000; done`
7. to test loadbalancer, `for i in {1..20}; do curl -o /dev/null -s -w "%{http_code}\n" -k -H "Host: hg.python.org" https://192.168.50.19/; done`

Fix local dev

---

salt/hg/config/remoteip.apache.conf.jinja
salt/hg/init.sls

This PR introduces a globally applied `mod_remoteip` configuration for handling client IPs, preparing for future rate-limiting configurations. It also specifies a salt state to manage `remoteip.conf`, creates a symlink to define the configuration, and another symlink to enable the configuration.
To verify these changes locally: 
1. bring up the salt-master, `laptop:psf-salt user$ vagrant up salt-master`
2. bring up the loadbalancer, `laptop:psf-salt user$ vagrant up loadbalancer`
3. bring up hg, `laptop:psf-salt user$ vagrant up hg`
4. in another window, ssh into the vagrant hg box, `laptop:psf-salt user$  vagrant ssh hg`
5. in another window, from your local computer, run the curl command `curl -k https://127.0.0.1:20010/hello -H "Host: hg.python.org"`
6. in the vagrant box, run `sudo …

mod_remoteip for X-Forwarded-For handling 

---

salt/haproxy/config/haproxy.cfg.jinja

This will allow for more indepth debugging of what's going on with the DigitalOcean loadbalancer and how it is interacting with haproxy's X-Forwarded-For handling.
Currently hg.python.org _should_ be seeing such headers and acting accordingly thanks to https://github.com/python/psf-salt/pull/324, but as is it is not working :(

Begin logging X-Forwarded-For in haproxy frontends

---

pillar/base/codespeed.sls

The current state of the branch requires Python 3.8+.

Temporarily run old speed.python.org

---

salt/base/repo.sls
salt/datadog/init.sls
salt/nginx/init.sls

older versions of Ubuntu that we currently support/run do not play nicely with the changes added to address apt-key deprecation.
this guards the new changes and applies them only to jammy boxes

guard older distros from jammy aptkey support

---

pillar/base/bugs.sls
salt/bugs/config/postfix/main.cf
salt/bugs/config/postfix/reject_recipients
salt/bugs/config/postfix/virtual
salt/bugs/init.sls

implement inbound email reports for roundup

---

pillar/base/users.sls

See: https://peps.python.org/pep-0745/

Add downloads/docs access for the release manager of Python 3.14 and 3.15 (3.26?)

---

salt/cdn-logs/init.sls

The `adm` group is used to control access to reading streamed logs, but isn't available for salt to fulfill the requisite.

cdn-logs: ensure adm group is applied to fastly logs

---

salt/buildbot/config/nginx.conf.jinja

It's already rewritten out in the location / config.

buildbot: Remove /all redirect

---

salt/buildbot/config/nginx.conf.jinja

This allows wss://buildbot.python.org/all/ws to load again.

buildbot: Move /all rewrite out of location /

---

pillar/base/firewall/salt.sls

- Adds firewall rules for host living outside of primary DC (NYC1)

feat(noble): add firewall rules for noble host migration

---

dockerfiles/Dockerfile.noble
salt/base/config/sources.list.jinja
salt/base/repo.sls
salt/base/salt.sls
salt/nginx/init.sls
salt/postgresql/base/init.sls

- Adds the bare minimum support for Noble without affecting any systems on other OS levels

feat: base support for noble

---

salt/base/salt.sls

Currently we get two things in `/etc/apt/source.list.d/`:
- `salt.list`
- `saltstack.list`
this is not fun
make it fun, squish into one

feat(base): ensure only one apt source for salt repo

---

salt/_grains/detect_virt.py

This is useful for things we may not want or be able to run when operating in a docker container.
Specific example is systemd-timesyncd, which refuses to start in a container:
```
[Unit]
Description=Network Time Synchronization
Documentation=man:systemd-timesyncd.service(8)
ConditionCapability=CAP_SYS_TIME
ConditionVirtualization=!container
DefaultDependencies=no
...
```
Note the `ConditionVirtualization` blocking.
Useful state might be something like:
```
systemd-timesyncd:
pkg:
- installed
service:
- enabled
{% if grains["detect_virt"] not in ["docker"] %}
- running
{% endif %}
```
Which would _enable_ the service but not fail when it fails to start.

implement a `detect_virt` grain

---

salt/base/sanity.sls

- Does not install ntp on noble as it uses timesyncd as an ntp client and running highstate in production causes conflicts

fix(base): disable ntp installed on noble

---

pillar/base/bugs.sls

- Renames the now stale URL for the retired cia.vc service. The domain has since been repurposed and is pointing to advertisements.
- Closes #399

chore(#399): remove `cia.vc` domain

---

pillar/base/firewall/loadbalancer.sls
pillar/base/haproxy.sls

- Fixes SMTP access with loadbalancers firewalls
- Corrects SMTP port for haproxy

fix(bugs): fix smtp haproxy config, allow smtp through lb firewall

---

salt/bugs/config/nginx.conf.jinja
salt/haproxy/config/haproxy.cfg.jinja

- Adds an include for fastly_params that will pull/inject real IPs for our nginx service
- Closes #368

fix(bugs): properly reveal ip downstream

---

Vagrantfile
pillar/base/firewall/bugs.sls
pillar/base/firewall/loadbalancer.sls
pillar/base/haproxy.sls
salt/bugs/config/postfix/main.cf
salt/bugs/config/postfix/master.cf
salt/bugs/init.sls
salt/haproxy/config/haproxy.cfg.jinja

This enables our haproxy instances to accept proxy protocol. This will be necessary so that we can get actual client ip addresses to the backends when requests traverse the Digital Ocean load balancers.
As is, haproxy _only_ sees the client address as the DO load balancer when clients hit it directly. With this, we can enable Proxy Protocol on the DO load balancer and send the actual client ip along.

Proxy protocol

---

salt/hg/init.sls

according to docs its for `clean` and not what i was thinking
- Remove `exclude_pat` causing issues
(Rack up more commits on the repo... /s... much shame on family)

fix(hg): remove exclude pattern

---

pillar/prod/backup/hg.sls

- Adds `/usr/share/mercurial/templates/static/` to backup directive for `hg` service
- Closes #440

feat(hg): add mercurial static files to backup

---

salt/datadog/init.sls

- Fixes issue with `pythontest` installing nginx and requiring manual intervention

fix(datadog): install datadog signing keys package before agent

---

pillar/prod/backup/hg.sls

- Adds `svn` config dir to backups

fix(hg): add svn backup configs required for new host setup

---

salt/pythontest/init.sls

- Adds a state to create the `/nonexistent/` directory used by FTP and/or NGINX based on the old host:
```
coffee@pythontest:/nonexistent$ stat .
File: .
Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fc01h/64513d    Inode: 2580481     Links: 2
Access: (0755/drwxr-xr-x)  Uid: (  113/   nginx)   Gid: (  118/   nginx)
Access: 2024-08-07 19:04:29.518055247 +0000
Modify: 2019-02-26 19:51:29.958493645 +0000
Change: 2019-02-26 19:51:29.962493645 +0000
Birth: -
```

fix(pythontest): add `nonexistent/` dir

---

salt/buildbot/init.sls

- Ensures parent directories exist
```
----------
ID: /data/www/buildbot
Function: file.directory
Result: False
Comment: No directory to create /data/www/buildbot in
Started: 16:28:20.978710
Duration: 1.918 ms
Changes:
----------
/data/www/buildbot:
----------
directory:
new
```
Build fast break fast :(

fix(buildbot): ensure parent dirs exist

---

salt/backup/client/init.sls

Looks like the version of rdiff-backup from noble emits warnings when run
```
WARNING: this command line interface is deprecated and will disappear, start using the new one as described with '--new --help'.
```
This address that.
_After_ we upgrade the backup server, we'll also need to edit the interior call. Filing #458 to track.

update rdiff-backup client call with new syntax

---

pillar/prod/swapfile.sls
salt/base/swap.sls
salt/datadog/init.sls

- Requires swap state to run before the doge
- Renames some things to be non-generic

feat: require swap to run before datadoge

---

salt/datadog/init.sls

- Adds check for datadog package half installed
- ```
root@consul-a-2404:~# stat /etc/datadog-agent/datadog.yaml
stat: cannot statx '/etc/datadog-agent/datadog.yaml': No such file or directory
root@consul-a-2404:~# dpkg --remove --force-remove-reinstreq datadog-agent || true
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: package is in a very bad inconsistent state; you should
reinstall it before attempting a removal
(Reading database ... 83527 files and directories currently installed.)
Removing datadog-agent (1:6.53.0-1) ...
root@consul-a-2404:~# apt-get -y --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded. 
```
- Fixes path check …

fix: ensure datadog is in good state, fix swap file path check

---

pillar/base/firewall/salt.sls

- Adds new backup server
- Removes old pythontest pinhole

feat: allow new backup server through

---

pillar/base/codespeed.sls

PyPy has moved to git. This will make the logs show.
See for instance https://speed.pypy.org/changes/?rev=a02837db72&exe=8&env=3 which fails to display. I no longer have permissions to access the live logs to see if this is part of the problem, but locally this fixes the page.

use git not hg for PyPy

---

salt/planet/config/nginx.planet.conf.jinja
salt/planet/init.sls

- Finishes transfer of ssl cert handling to haproxy instead of lego
- Closes python/planet#571

fix(planet): remove lego in favor of haproxy

---

salt/ssh/init.sls

Adds /usr/lib/tmpfiles.d/sshd-priv-sep.conf to ensure that /run/sshd exists on all boots.
- Addresses #478

ensure that the sshd privilege separation directory exists

---

pillar/dev/secrets/fastly.sls
salt/haproxy/init.sls

This allows us to have multiple concurrent fastly tokens so we can perform a rotation.

loadbalancer: enable multiple fastly-tokens at once for key rotation

---

salt/backup/server/init.sls
salt/ssh/configs/sshd_config.jinja

mail.ams1.psf.io is using ssh-rsa still, which isn't ideal but we need to accept it in the short term until it is upgraded.
without this, backups fail with:
```
ERROR: Couldn't start up the remote connection by executing 'ssh -i /etc/backup/.ssh/id_rsa_mail-python-org -C [mail-python-org@backup.sfo1.psf.io](mailto:mail-python-org@backup.sfo1.psf.io) rdiff-backup server'
due to exception 'Truncated header <b''> (problem probably originated remotely)'.
```

backup: accept older public key algorithms

---

pillar/dev/consul.sls
salt/haproxy/config/consul-recursors.json
salt/haproxy/init.sls

PR #486 introduced resolution of hosts for haproxy backends via consul, but did not give it any way to resolve external DNS for the console/pythonanywhere or jobs.pyfound.org/applytojob.com backends.
This adds a recursive DNS setup on the haproxy nodes so that they can successfully and fully resolve external services.

Allow Consul DNS to recurse on haproxy nodes

---

salt/docs/config/nginx.docs-backend.conf

I was looking at the docs' NGINX config as part of seeing if #287 is feasible and noticed these redirects are out of date.
A

Update devguide redirects

---

salt/docs/config/nginx.docs-backend.conf

Previous mass removals of modules have had redirects, we can do the same for PEP 594:
https://github.com/python/psf-salt/blob/20e0021e000b8ca670def1d7e9ebfdaefa64ff4a/salt/docs/config/nginx.docs-backend.conf#L53-L55
Note we can't have `3|` yet -- needs to be added post 3.13.0 release.
A

Redirect dead batteries

---

salt/buildbot/init.sls

- Restore the cache refresh request cronjob from the old host that was never properly added to Salt.

buildbot: Add release dashboard cache refresh request cronjob

---

salt/docs/init.sls

xref:
* https://github.com/python/docs-community/issues/131
* https://github.com/python/docsbuild-scripts/pull/199

Restore the HTML docsbuild cron job

---

salt/docs/config/nginx.docs-backend.conf
salt/docs/init.sls

Error introduced in #504, our nginx config includes conf.d/* and that caused this to choke on deploy.

fix docs redirects include configuration

---

salt/docs/config/nginx.docs-redirects.conf
tests/docs-redirects/specs/surrogate-key.hurl

Use Surrogate-Key headers for docs.python.org

---

salt/docs/init.sls

The English docs are more popular by an order of magnitude per the [plausible statistics](https://plausible.io/docs.python.org/pages).
We increase rebuild of English-only to twice per hour, decrease other languages to daily, and decrease the non-HTML archives builds to every other day.
A

Add an English-only docsbuild scheduled job

---

salt/docs/init.sls

cc @JacobCoffee 
I forgot to make the identifier distinct, which means crontab is now inconsistent:
```bash
$ sudo crontab -l -u docsbuild
[...snip...]
7 6 */2 * * /srv/docsbuild/venv/bin/python /srv/docsbuild/scripts/build_docs.py --select-output=no-html
16,46 * * * * /srv/docsbuild/venv/bin/python /srv/docsbuild/scripts/build_docs.py --select-output=only-html-en --language=en
```
A

Fix indentifier

---

salt/docs/config/nginx.docs-redirects.conf
tests/docs-redirects/specs/py2.5.hurl

This flattens multiple redirects in the Python 2.5 redirects.
We also remove redirects for `/dist/` and `/inst/` as `/distutils` and `/install` have been removed as pages on the website.
A

Avoid multiple redirects in pre-2.5 paths

---

pillar/dev/secrets/docs.sls
salt/docs/init.sls

Towards #287. #510 implements Surrogate-Keys for docs responses, this will allow for the docsbuild scripts to issue purges against the API when they are updated.

expose fastly purge configuration for docsbuild

---

salt/docs/config/nginx.docs-redirects.conf
tests/docs-redirects/specs/PEP-594.hurl

Followup to #496, `/3/` is now Python 3.13.
Tests have been added.
A

Redirect PEP 594 dead batteries (part 2)

---

tests/docs-redirects/specs/top-level-directories.hurl

Add tests for the 'deprecations' redirect

---

pillar/base/bugs.sls

Change logging level to warning due to 'Internal Server Error'
EE manual changed logging to level INFO. Restarting to make INFO live cleared the issue. ERROR was the original logging level, but left us with no info for debugging. Try WARNING log level to see if that gives more info if this happens again. INFO is too verbose.
The irc report:
```
2024-11-20 09:55:03 rouilj: ee, we are getting an 'Internal Server
Error' on the roundup issue tracker when trying to update
issues. /var/log/nginx/error.log,
/var/log/nginx/roundup-roundup.error.log are empty and
/var/log/roundup/tracker_roundup.log hasn't been updated since oct
27th. This was working on 2024-11-14 at 9:48 ET. Ideas on where else I
should look or any changes done since then?
```
-
-

Update bugs.sls - change roundup tracker to WARNING log level

---

salt/cdn-logs/config/fastly.logrotate.conf

finally figured out why our log rotate on cdn-logs was all goofy and we were always seeing logs appended to `.1` instead of the expected file :)

update logrotate config for cdn-logs

---

salt/base/salt.sls

- ensure that the apt keyrings directory exists before placing file

fix: ensure apt keyring dir exists

---

salt/bugs/init.sls

- Adds group write bit for cloned repos 
- Closes #528

feat(#528): allow `roundup` group users to interact with git repos

---

salt/bugs/config/nginx.conf.jinja

The current config is leading to some rate limiting of the load balancers doing their health checks, which is a major reason bugs.python.org has been so flappy 🤦🏼

Adjust rate limit for roundup backends

---

salt/haproxy/config/haproxy.cfg.jinja

This condition was in place to support the proxy nonsense we had going that was removed in https://github.com/python/psf-salt/pull/543, we can go ahead and always set this now that our frontend is handling tls

always set x-client-ip from frontend

---

pillar/dev/secrets/bugs.sls
pillar/dev/top.sls
salt/bugs/config/config.ini.jinja

Towards #546, allows us to set SMTP settings on a per-tracker basis.
Adds some sample secrets for roundup to emulate what we have in prod and demonstrate this feature.

bugs: allow configuration of smtp per tracker

---

salt/docs/init.sls

d.p.o builds are failing as the server runs Python 3.10, which Sphinx 3.2 has just dropped support for.

Upgrade docsbuild Python to 3.13

---

pillar/base/users/adam.sls

Following up on the proposed wiki work from the most recent documentation meeting, we're exploring a `git` replica of the wiki content. Better to do this via the data dump than taxing the already-overloaded web server.

Add moin access to `adam.sls`

---

pillar/base/haproxy.sls

Reverts python/psf-salt#553
This caused salt to start failing on lbs, which let their certs expire:
```
ee@lb-1:~$ sudo salt-call state.highstate
local:
Data failed to compile:
----------
Pillar failed to render with the following messages:
----------
Rendering SLS 'haproxy' failed. Please see master log for details.
```

Revert "feat: add rate limit to wiki services"

---

pillar/base/haproxy.sls

- i tested it this time 🥲
```
correct state
loadbalancer:      Started: 17:22:45.765876
loadbalancer:     Duration: 3.187 ms
loadbalancer:      Changes:
loadbalancer: 
loadbalancer: Summary for local
loadbalancer: --------------
loadbalancer: Succeeded: 181 (changed=1)
loadbalancer: Failed:      0
loadbalancer: --------------
loadbalancer: Total states run:     181
loadbalancer: Total run time:     7.156 s
psf-salt [📝🤷✓] via  pyenv via ⍱ v2.4.3 took 2m27s 
➜ vu loadbalancer
Bringing machine 'loadbalancer' up with 'docker' provider...
==> loadbalancer: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> loadbalancer: flag to force provisioning. Provisioners marked to run always will still run.
==> loadbalancer: Running provisioner: shell...
loadbalancer: …
```

feat: add rate limit to wiki services

---

salt/docs/init.sls

docsbuild-scripts expects the languages flag to be ``--languages``, not ``--language``. We want to remove the singular variant, so this updates the usage to allow removal upstream.
A

Use the correct spelling of the ``--languages`` flag

---

salt/docs/config/docsbuild-scripts
salt/docs/init.sls

Make environment variables specific to docs.python.org available as a configuration file to ensure they're used no matter how the script is invoked.
Note: This limits access to the file to user/group `docsbuild`
Ref: https://github.com/python/docsbuild-scripts/pull/269
Ref: https://github.com/python/docsbuild-scripts/pull/266

Docsbuild config

---

pillar/base/planet.sls
salt/planet/config/run-planet.sh.jinja
salt/planet/init.sls

By building and publishing containers for the Python 2 and Python 3 variants, we can just run the actual jobs in Docker.
Py2 image: https://github.com/python/planet/pull/596
Py3 image: https://github.com/python/planet/commit/4cd16ca96927e34a2954b662e4dc0162d8b1d49b

run planet from dockerized containers, unblock dist upgrade

---

salt/hg/config/hg.apache.conf.jinja
salt/hg/files/hg/src/hgrev.py
salt/hg/files/hg/wsgi/rev.wsgi

hgweb is pummeled by scrapers/bots and has just out lived its usefulness.
This serves our hg repos from apache directly as static http. clones still work.
This restores 1 piece of hgweb we need, which is the revision viewer, via a WSGI app that wraps `hg log` to provide a way to view a single commit. the current /lookup route relies on this.

serve hg more statically

---

pillar/prod/top.sls

- New deploy doesn't actually work because we don't source it in the pillar data i think

fix: make sure we source sentry secrets in prod

---

docs/guides/external-host-requirements.md

fix: update links rendering

---

salt/postgresql/base/init.sls

- focal is EOL, so pgsql people moved focal repos into `apt-archive` (https://apt-archive.postgresql.org/pub/repos/apt/dists/index.html)
```
salt-master: Summary for local
salt-master: --------------
salt-master: Succeeded: 220 (changed=51)
salt-master: Failed:      0
salt-master: Warnings:    2
salt-master: --------------
salt-master: Total states run:     220
salt-master: Total run time:    58.223 s
```
-

fix: update to apt-archive for pg11 on ubuntu focal

---

salt/docs/init.sls

We currently build ~every 48 hours. This changes the non-HTML (PDF, EPUB, TexInfo, Text) documentation builds to be every nine days, or roughly thrice per month.
A

Reduce frequency of non-HTML documentation builds

---

docs/conf.py
docs/requirements.txt
docs/salt-server-list.rst
pillar/prod/roles.sls
salt/base/config/salt-server-list.rst.jinja

adds categories, search, and sorting to server list

Server list categories
