python/psf-salt

- pillar/prod/top.sls
- salt/pydotorg/config/django-settings.py.jinja
> Add FASTLY_API_KEY to django settings

- salt/pydotorg/init.sls
- Requested https://github.com/python/pythondotorg/issues/557
> Speed up PEP deploy frequency

- salt/pydotorg/config/bash_profile
- salt/pydotorg/init.sls
Fixes generated CSS and JS file permissions.
> Fix pydotorg user umask

- pillar/base/pydotorg/prod.sls
- pillar/base/pydotorg/staging.sls
Revert the hardening changes to restore pydotorg to a normal umask.
> Pydotorg umask fix

- salt/haproxy/config/haproxy.cfg.jinja
> GNU Terry Pratchett

- pillar/base/pydotorg/staging2.sls
Change staging2 to use staging2 branch.
> Change staging2 branch

- salt/pydotorg/config/pydotorg.nginx.jinja
Reported https://github.com/python/pythondotorg/issues/741
> Fix old legacy PEP redirects

- salt/pycon/init.sls
So we can see each job's result.
> Put cron job logs in separate files

- salt/pycon/config/pycon_worker.upstart.conf.jinja
- salt/pycon/init.sls
Pycon site needs background workers for Celery.
> Run Celery worker for Pycon

- pillar/base/users.sls
As requested.
For out of band confirmation, I've asked @brandon-rhodes to supply this key via github. As soon as It's seen at https://github.com/brandon-rhodes.keys I'll be merging and deploying this Pull-Request.
> add @brandon-rhodes for pycon access

- pillar/base/users.sls
> Added scottlee to Salt users.

- salt/pydotorg/config/pydotorg.nginx.jinja
Fixes https://github.com/python/pythondotorg/issues/928
> Serve *.py files as text/plain

- pillar/base/users.sls
Replace my old RSA key with a new ed25519 key.
> haypo: Change my SSH key

- salt/haproxy/config/nginx-redirect.conf.jinja
CT is a significantly more powerful tool for ensuring a safe ecosystem.
> Remove HPKP support, it's mostly a bad idea at this point

- salt/planet/config/nginx.planet.conf.jinja
add ssl planetpython.org, will fix styling issues after.
> update nginx config for planetpython.org

- pillar/base/planet.sls
comment planet.jython.org no dns record
> comment planet.jython.org no dns record

- salt/docs/init.sls
> docs: setup python3.6 for docsbuild

- salt/slack-irc/config/slack-irc.json.jinja
update pythondotorg slack-irc channel settings
> update pythondotorg slack-irc channel settings

- salt/slack-irc/config/slack-irc.json.jinja
> adding AUTH support

- docs/overview.rst
add Ernest as Chair sort by alpha
> staff changes

- salt/pypa/bootstrap/init.sls
re: https://github.com/pypa/pip/issues/5093#issuecomment-374996261
> add 2.6 to bootstrap

- salt/pypa/bootstrap/init.sls
also enables purging for 2.6 :)
> add python 3.3 to bootstrap

- Vagrantfile
- salt/base/salt.sls
- salt/pydotorg/init.sls
- salt/pypa/bootstrap/init.sls
- salt/speed/web/init.sls
- tasks/salt.py
Gets us up to date on salt releases, tidies up some lingering issues.
> upgrade to salt 2018.3

- salt/pydotorg/config/pydotorg-uwsgi.ini.jinja
See https://github.com/getsentry/raven-python/issues/732#issuecomment-176854438 for more details.
> Avoid errors on aborted client connections

- pillar/dev/secrets/docs.sls
- pillar/dev/top.sls
- pillar/prod/top.sls
- salt/docs/init.sls
to support https://github.com/python/docsbuild-scripts/pull/61
> add a SENTRY_DSN for docsbuild cronjobs

- salt/docs/config/nginx.docs-backend.conf
fixes https://github.com/python/psf-salt/issues/147
> A few redirections to get less 404 flood in the logs.

- salt/docs/config/nginx.docs-backend.conf
typically:
/lib/module-subprocess.htmlAvoid
/lib/module-sqlite3.html
/lib/module-SimpleHTTPServer.html
/lib/module-ConfigParser.html
> A few more redirections to get less 404 flood

- pillar/base/users.sls
I copied options that @ned-deily (nad) has above.
> Add myself as 3.8.0 RM

- salt/docs/init.sls
see: https://bugs.python.org/issue35528
> Add new Sphinx 2 / xelatex dependency.

- pillar/base/codespeed.sls
compliment to https://github.com/python/codespeed/pull/1
> updates for speed.pypy.org

- pillar/base/users.sls
If any proof is needed I'll gladly share a selfie with my new key :-]
> Julien Palard: New Yubikey.

- pillar/base/users.sls
We need to remove some spam from the tracker and to obliterate it I need shell access.
> Allow rouilj access to manage roundup tracker.

- salt/docs/init.sls
> New dependency to build doc: texinfo.

- salt/pypa/bootstrap/init.sls
Toward https://github.com/pypa/get-pip/issues/83
> Add get-pip.py for Python 3.5

- salt/buildbot/init.sls
See https://github.com/python/buildmaster-config
> buildbot switched to main branch

- pillar/base/users.sls
@malemburg please confirm the details below.
> add user for Marc-Andre Lemburg

- pillar/base/users.sls
grant access to necessary docs groups for exploration
> upgrade Chloe access for docs

- pillar/dev/roles.sls
- pillar/prod/roles.sls
- salt/_extensions/pillar/ca.py
- salt/_extensions/pillar/consul.py
- salt/base/config/salt-roles.conf.jinja
- salt/base/salt.sls
- salt/consul/init.sls
- salt/postgresql/server/init.sls
- salt/users/init.sls
These necessary state changes will modify anywhere the roles key from pillar is accessed.
> Necessary state changes 

- salt/base/config/known_hosts.jinja
- salt/base/salt.sls
> Generate a known_hosts file for servers in the infrastructure from salt server's perspective.

- salt/codespeed/init.sls
invocation: `tox -e lint $(find salt/codespeed -type f -name '*.sls'| xargs)`
> salt-lint the salt/codespeed directory

- pillar/base/users.sls
cc @malemburg, you can access at planet.nyc1.psf.io
> Grant access for Marc-Andre to the planet host

- salt/backup/client/init.sls
- salt/backup/server/init.sls
- salt/bugs/init.sls
- salt/buildbot/init.sls
- salt/cdn-logs/init.sls
- salt/codespeed/init.sls
- salt/datadog/init.sls
- salt/sudoers/init.sls
- salt/users/init.sls
https://github.com/warpnet/salt-lint/commit/42669e8b493492e005a15ed083f64172fe10aaed added new rule for over-indenting nested dictionaries. comply with that rule!
> upgrade for latest salt-lint rules

- pillar/base/firewall/salt.sls
- salt/bugs/config/nginx.conf.jinja
- salt/tls/pebble.sls
Configure bugs server to allow for nginx rate-limiting.
> Rate limit

- Dockerfile
This adds Vim to our Dockerfile for convenience purposes.
> Install Vim for our vagrant boxes

- pillar/base/users.sls
Hello,
I triage Buildbot results as part of my Deputy Developer in Residence job. I'd appreciate having access so I can apply config changes effectively.
> Add user for Petr Viktorin with buildbot access

- salt/docs/init.sls
re: https://github.com/python/cpython/issues/120074#issuecomment-2153425802
> Add env var to enable docs analytics

- docs/overview.rst
- Updates infra team 
- fix(docs): typo
> docs: add new guy

- docs/guides/haproxy-registration-guide.md
- docs/guides/migration-recipe.md
- docs/guides/port-guide.md
- docs/guides/server.rst
- Updates the `docs/guides/` sections with small changes for easier copypasta
- fixes some outdated info
- fixes markdown syntax
> docs: update guides

- docs/conf.py
- docs/requirements.txt
- Adds sphinx-copybutton, which will render clickable copy buttons to code blocks. Helpful for grabbing strings quickly to reduce human error (assuming our docs are correct :P)
> docs: add copybutton to code blocks

- .github/workflows/deployminder.yml
Adds a reminder comment from GH actions to manually deploy changes
> ci: add a reminder to manually deploy merged changes

- pillar/prod/roles.sls
Updates role information to accept new hosts
> docs: update role metadata

- salt/datadog/init.sls
- Adds missed tree for datadog noble support
> fix(datadog): add missing tree for base support on noble

- .github/PULL_REQUEST_TEMPLATE.md
- docs/guides/migration-recipe.md
- Add explicit details for data migrations
- Moves some sections into lower levels under parent sections
- Add PR template
> docs: add some details to docs, lower sections into relevant subsections

- pillar/base/haproxy.sls
- Reverts method of importing pillar data for bugs
> fix(bugs): revert to yaml import

- docs/guides/migration-recipe.md
- Add required `salt-minion` specifier to service restart
- Closes #339
> fix(docs): update salt minion service restart instruction

- Vagrantfile
- salt/hg/config/repos.conf
- salt/hg/files/hg/wsgi/python.wsgi
- salt/hg/init.sls
- Upgrades `hg` to Ubuntu 24.04 Noble
- Closes #414
> feat(hg): working hg on noble

- salt/hg/files/hg/wsgi/python.wsgi
- salt/hg/init.sls
- Fixes issue with pre-Ubuntu 24.04 Noble support that was missed in #403
> fix(hg): add branches for noble

- salt/hg/files/hg/wsgi/python.wsgi
- salt/hg/files/hg/wsgi/python3.wsgi
- salt/hg/init.sls
- Further fixes that I failed to do in #428
> fix(hg): add file branch for wsgi file

- salt/hg/init.sls
- Fixes OS check for list vs string
- Fixes bad git conflict stomping due to me being not smart and using the GitHub UI thinking it was good but in fact is bad
> fix(hg): make os check a string, fix git conflict mess

- docs/guides/migration-recipe.md
- Adjusts command for rsyncing backup data
> fix(docs): adjust command for transferring backup data

- salt/hg/init.sls
- Fixes twice-reverted code due to git conflict
> fix(hg): fix git conflict mess again

- salt/datadog/init.sls
> revert: undo pkg requirement

- Vagrantfile
- salt/buildbot/init.sls
- Upgrades `buildbot` to Ubuntu 24.04 Noble
- Closes #413
> feat(buildbot): working `buildbot` on noble

- docs/guides/migration-recipe.md
- Adds shoutout to not be a silly goose and use ssh forwarding
-  Closes #436
> docs(#436): add shoutout to ssh forwarding

- pillar/prod/backup/buildbot.sls
> fix(buildbot): re-enable backups for buildbot service

- docs/guides/migration-recipe.md
- Ensures salt minion service restarts fully
> docs: change command for service restart

- pillar/base/firewall/ftp.sls
- salt/pythontest/config/vsftpd.conf
- Adds 100 ports instead of 10 due to python/cpython#122795
> feat: add more ports for incoming ftp connections

- pillar/prod/swapfile.sls
- pillar/prod/top.sls
- salt/base/swap.sls
- salt/top.sls
- Adds swap with configurability via pillar datum
https://serverfault.com/a/865797
- Closes #449
> feat(#449): add swap space by default

- salt/base/swap.sls
> fix(#449): fix check for path

- salt/datadog/init.sls
- Defines swap state vars in datadog state
> fix: define swap vars in datadog state

- pillar/prod/consul.sls
> fix: update to new hostnames

- salt/backup/client/init.sls
- salt/backup/server/init.sls
- Migrate to new command
- Closes #458
> feat: migrate to new rdiff command

- salt/backup/client/init.sls
> update exclude syntaxt for rdiff-backup 2.2.6

- salt/backup/server/init.sls
Updates syntax for backup cleanup jobs
> backup: rdiff-backup update cleanup syntax

- pillar/prod/top.sls
Updates pillar/prod/top.sls to enable #484
> followup to #484 to enable functionality

- pillar/base/users.sls
As discussed/suggested on the core dev discord (cc @hugovk).
A
> Add docs access for Adam Turner

- salt/_extensions/pillar/dms.py
- Increase highstate failure interval checks to an hour
-
> chore: increase interval for snitching

- salt/planet/init.sls
temporary measure while https://github.com/python/planet/pull/577 is in progress
> Pin planet

- salt/docs/init.sls
> Install texlive-fonts-extra in docsbuild

- salt/base/salt.sls
> fix: ensure repo key exists with right perms

- salt/base/salt.sls
> fix: close loop properly

- pillar/base/haproxy.sls
- Increase the rate limit for roundup trackers to not be so aggressive
> chore: increase rate limit to not be so aggressive

- pillar/base/bugs.sls
> update issues.roundup-tracker.org to send from roundup-tracker.org

- pillar/base/haproxy.sls
- Adds rate limit for `moin` per @malemburg's request
> feat: add rate limit to wiki services

- salt/base/swap.sls
Fixes #564
- Makes swap config not so smart
> fix(#564): make swap config one shot

- pillar/base/planet.sls
- salt/planet/config/nginx.planet.conf.jinja
> fixup planet nginx

- pillar/base/users/_admin/ee.sls
work laptop is locked in the staff office and I wanna do stuff lol
> Add my personal laptop key

- pillar/base/users/offby1.sls
-------
- Add user access for me to planetpython's host
/cc @JacobCoffee
> Add a personal access key for planet access

- salt/hg/files/hg/src/hgrev.py
debugging a memory leak in hgrev
> hg: add check=True to hgrev subprocess run

- pillar/base/users/diegorusso.sls
I've also given myself access to codespeed as in the past I worked with it and very likely I will need it in the near future.
> Add diegorusso to the list of users

- salt/hg/files/hg/src/app.py
> hg: missed a spot

- salt/docs/config/nginx.docs-redirects.conf
- tests/docs-redirects/specs/PEP-594.hurl
- tests/docs-redirects/specs/default-root.hurl
- tests/docs-redirects/specs/surrogate-key.hurl
Bengali, Greek, and Romanian are new translations. Tests updated.
> Add redirects for new translations

- pillar/base/users/savannah.sls
Related to https://discuss.python.org/t/welcome-the-3-16-and-3-17-release-manager-savannah-bailey/100163! Looks like things have changed a bit since Hugo last did this in https://github.com/python/psf-salt/pull/356 but I think this is correct.
> Add Savannah for downloads and docs server access
